# Generated by Django 6.0.6 on 2026-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(default='MBBS', max_length=150),
            preserve_default=False,
        ),
    ]
