# Generated by Django 6.0.6 on 2026-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_doctors_available_doctors_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_image',
            field=models.ImageField(default='department.jpeg', upload_to='departments/'),
            preserve_default=False,
        ),
    ]
