# Generated by Django 6.0.6 on 2026-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_image',
            field=models.CharField(max_length=100),
        ),
    ]
